/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#26fedc",
        "secondary-fixed-dim": "#b1c5ff",
        "secondary": "#b1c5ff",
        "on-secondary-fixed": "#001946",
        "secondary-fixed": "#dae2ff",
        "on-primary-container": "#00566a",
        "surface-tint": "#4cd6ff",
        "inverse-primary": "#00677f",
        "outline-variant": "#3c494e",
        "inverse-on-surface": "#2c3136",
        "on-secondary-container": "#a6beff",
        "on-error": "#690005",
        "on-background": "#dee3ea",
        "on-surface-variant": "#bbc9cf",
        "on-tertiary-container": "#00594c",
        "surface-container": "#1b2025",
        "error-container": "#93000a",
        "on-tertiary": "#00382f",
        "tertiary-fixed-dim": "#00dfc1",
        "primary-fixed-dim": "#4cd6ff",
        "on-secondary": "#002c70",
        "surface-variant": "#30353b",
        "on-tertiary-fixed-variant": "#005144",
        "secondary-container": "#0148ab",
        "surface-container-low": "#171c21",
        "surface-container-highest": "#30353b",
        "primary-container": "#00d1ff",
        "error": "#ffb4ab",
        "on-surface": "#dee3ea",
        "on-primary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#00419e",
        "tertiary-container": "#00d8bb",
        "surface-container-high": "#252a30",
        "on-primary-fixed-variant": "#004e60",
        "primary-fixed": "#b7eaff",
        "surface-bright": "#353a3f",
        "tertiary": "#0ef7d6",
        "surface-dim": "#0f1419",
        "outline": "#859399",
        "on-tertiary-fixed": "#00201a",
        "background": "#0f1419",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dee3ea",
        "primary": "#a4e6ff",
        "on-primary": "#003543",
        "surface-container-lowest": "#0a0f14",
        "surface": "#0f1419"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
