import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: { code: 'METHOD_NOT_ALLOWED', message: 'POST only' } });
  }

  const { propertyName, address, city, state, country, marketValue, liquidityScore, capRate, occupancyRate, timeToLiquidity, assessments } = req.body || {};

  // Generate a simple HTML report and convert to downloadable file
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>LiqUIFI Report - ${propertyName || 'Property'}</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; margin: 40px; color: #1a1a2e; }
    h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
    h2 { color: #334155; margin-top: 24px; }
    .metric { display: inline-block; margin: 12px 24px 12px 0; padding: 16px 24px; background: #f1f5f9; border-radius: 8px; }
    .metric .value { font-size: 28px; font-weight: 700; color: #6366f1; }
    .metric .label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
    .assessment { padding: 12px 0; border-bottom: 1px solid #e2e8f0; }
    .assessment .title { font-weight: 600; }
    .positive { color: #22c55e; } .neutral { color: #f59e0b; } .negative { color: #ef4444; }
    .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>🏢 LiqUIFI Liquidity Report</h1>
  <p><strong>${propertyName || 'Property'}</strong> — ${address || ''}, ${city || ''}, ${state || ''}, ${country || ''}</p>
  
  <h2>Key Metrics</h2>
  <div>
    <div class="metric"><div class="value">${liquidityScore ?? 'N/A'}</div><div class="label">Liquidity Score</div></div>
    <div class="metric"><div class="value">$${marketValue ? Number(marketValue).toLocaleString() : 'N/A'}</div><div class="label">Market Value</div></div>
    <div class="metric"><div class="value">${capRate ?? 'N/A'}%</div><div class="label">Cap Rate</div></div>
    <div class="metric"><div class="value">${occupancyRate ?? 'N/A'}%</div><div class="label">Occupancy</div></div>
    <div class="metric"><div class="value">${timeToLiquidity ?? 'N/A'} days</div><div class="label">Time to Liquidity</div></div>
  </div>

  ${assessments?.length ? `
  <h2>AI Assessments</h2>
  ${assessments.map((a: any) => `
    <div class="assessment">
      <span class="title ${a.sentiment}">${a.title}</span>
      <p>${a.detail}</p>
    </div>
  `).join('')}
  ` : ''}

  <div class="footer">
    Generated by LiqUIFI — Liquid Intelligence Framework<br>
    Report Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html');
  res.setHeader('Content-Disposition', `attachment; filename="liquifi-report-${(propertyName || 'property').replace(/\s+/g, '-').toLowerCase()}.html"`);
  return res.status(200).send(html);
}
